/**
 * Inlines templates/enhance.v1.md into src/generated/template.ts and records its
 * sha256, so the template ships inside bundles without any runtime file reads.
 *
 * Run via the `generate` script; `build` and `typecheck` both depend on it.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const TEMPLATE = 'enhance.v1.md';

const source = readFileSync(join(root, 'templates', TEMPLATE), 'utf8').replace(/\r\n/g, '\n');
const sha256 = createHash('sha256').update(source, 'utf8').digest('hex');

const outDir = join(root, 'src', 'generated');
mkdirSync(outDir, { recursive: true });

const out = `// GENERATED by scripts/generate.mjs — do not edit.
// Source: templates/${TEMPLATE}

export const TEMPLATE_SOURCE = ${JSON.stringify(source)};

export const TEMPLATE_SHA256 = ${JSON.stringify(sha256)};
`;

writeFileSync(join(outDir, 'template.ts'), out, 'utf8');

console.log(`generated src/generated/template.ts from ${TEMPLATE} (sha256 ${sha256.slice(0, 12)}…)`);
